import { type NextPage } from "next";
import Head from "next/head";
import Auth from "@components/Auth";
import Layout from "@components/Layout";




const Login: NextPage = () => {
  

  return (
    <>
      <Head>
        <title>AlwaysPanel | Inicio de Sesión</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div
          className="flex h-full w-full flex-col  items-center justify-start
        rounded bg-gradient-to-tr from-blue-50 to-violet-50 md:justify-center"
        >
          <h1 className="mt-10 text-center text-3xl font-bold text-gray-800 md:mt-0 md:text-7xl">
            Datos para mejorar tu{" "}
            <span className="ml-2 text-violet-700">trabajo</span>
          </h1>
          <p className="mt-6 p-2 text-center text-xl leading-8 text-gray-600 sm:text-center">
            La mejor manera para brindar un buen servicio es teniendo la mejor
            herramienta
          </p>
          <Auth />
        </div>
      </Layout>
    </>
  );
};

export default Login;
